//! Complex, real-world spreadsheets: pivot tables, charts/pictures/shapes/comments, hidden and
//! grouped rows, filters, merges, formulas, error values, number formats of every family, many
//! and oddly named sheets, encrypted files, a sheet over the row cap.
//!
//! The files live in `testdata/office/` and are **our own** (generated by `testdata/office/gen/`
//! with LibreOffice through UNO and with openpyxl; see its README). Each is read through the
//! production path (`load_workbook_sheet`) and what the grid shows is pinned.
//!
//! What konoma does NOT read (colours, borders, column widths, charts, pictures, shapes,
//! comments, conditional formats, validations, hidden rows/columns, outlines, filters, freeze
//! panes) is pinned as such: those tests say "current spec" in their names, so a change of spec is
//! a deliberate edit and not a silent one.
//!
//! Known bugs found while building these files are written as `#[ignore = "BUG: ..."]` tests that
//! assert the *correct* behaviour (so fixing the bug turns them green; see the report that came
//! with them). They are not pinned to the wrong output.
//!
//! The expected values for the pivot tables come from `testdata/office/expected/pivot.expected.json`,
//! computed by the generator from the source rows (not read back from the pivot).

use super::*;
use std::path::PathBuf;

// ---------------------------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------------------------

fn td(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/office")
        .join(name)
}

/// The path of a test file, or `None` (with a SKIP note) when `testdata/` is not there (the
/// published crate excludes it, like `samples/`).
fn file(name: &str) -> Option<PathBuf> {
    let p = td(name);
    if p.exists() {
        Some(p)
    } else {
        eprintln!("SKIP: testdata/office/{name} not found (excluded from the published crate)");
        None
    }
}

const EXTS: [&str; 3] = ["xlsx", "xls", "ods"];

/// The workbook with the cells of sheet `idx` loaded (production path).
fn open(path: &Path, idx: usize) -> Workbook {
    let wb = load_workbook_sheet(path, &LoadOptions::default(), idx)
        .unwrap_or_else(|e| panic!("{}: {e:?}", path.display()));
    assert!(
        wb.sheet_error.is_none(),
        "{}: sheet {idx}: {:?}",
        path.display(),
        wb.sheet_error
    );
    wb
}

fn names(wb: &Workbook) -> Vec<&str> {
    wb.sheets.iter().map(|s| s.name.as_str()).collect()
}

/// The display grid of the loaded sheet, trailing empty cells and rows trimmed.
fn grid(s: &Sheet) -> Vec<Vec<String>> {
    let mut g: Vec<Vec<String>> = (0..s.nrows)
        .map(|r| {
            let mut row: Vec<String> = (0..s.ncols).map(|c| s.display(r, c).to_string()).collect();
            while row.last().is_some_and(|x| x.is_empty()) {
                row.pop();
            }
            row
        })
        .collect();
    while g.last().is_some_and(|r| r.is_empty()) {
        g.pop();
    }
    g
}

/// Sheet `idx` of `file`: (workbook, index) so the caller can borrow the sheet.
fn sheet_wb(name: &str, idx: usize) -> Option<(Workbook, usize)> {
    let p = file(name)?;
    Some((open(&p, idx), idx))
}

fn json(name: &str) -> serde_json::Value {
    let p = td(&format!("expected/{name}"));
    serde_json::from_str(&std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{p:?}: {e}")))
        .unwrap()
}

fn num(s: &Sheet, r: usize, c: usize) -> f64 {
    match s.cell(r, c).map(|x| &x.value) {
        Some(CellValue::Int(i)) => *i as f64,
        Some(CellValue::Number(n)) => *n,
        other => panic!("not a number at r{} c{}: {other:?}", r + 1, c + 1),
    }
}

fn find_row(s: &Sheet, col: usize, text: &str) -> Option<usize> {
    (0..s.nrows).find(|&r| s.display(r, col) == text)
}

// ---------------------------------------------------------------------------------------------
// pivot tables
// ---------------------------------------------------------------------------------------------
//
// A pivot table is *cells* in the file (what the application computed when it saved), plus a pivot
// definition that konoma does not read. So konoma shows the saved aggregation as an ordinary grid:
// these tests pin that the values are exactly the sums computed from the source rows.

fn sums(exp: &serde_json::Value, key: &str, k: &str) -> f64 {
    exp[key][k].as_f64().unwrap_or_else(|| panic!("{key}/{k}"))
}

#[test]
fn pivot_sheets_are_listed_in_order_in_all_three_formats() {
    for ext in EXTS {
        let Some(p) = file(&format!("pivot.{ext}")) else {
            return;
        };
        let wb = open(&p, 0);
        assert_eq!(
            names(&wb),
            ["元データ", "ピボット", "ページ付き", "件数"],
            "{ext}"
        );
        assert_eq!(wb.hidden_sheets, 0, "{ext}");
    }
}

#[test]
fn pivot_source_data_is_complete() {
    let exp = json("pivot.expected.json");
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("pivot.{ext}"), 0) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!(s.nrows, 1 + exp["rows"].as_u64().unwrap() as usize, "{ext}");
        assert_eq!(
            grid(s)[0],
            ["地域", "商品", "月", "チャネル", "売上"],
            "{ext}"
        );
        // every source row sums to the expected grand total
        let total: f64 = (1..s.nrows).map(|r| num(s, r, 4)).sum();
        assert_eq!(total, exp["grand"].as_f64().unwrap(), "{ext}");
        // text with markup characters survives
        assert!(find_row(s, 1, "Pen & Ink <A>").is_some(), "{ext}");
    }
}

/// The main pivot (rows: region > product, columns: month, data: SUM of sales, with region
/// subtotals and grand totals): every cell is what the source rows add up to.
#[test]
fn pivot_main_table_matches_sums_computed_from_the_source_rows() {
    let exp = json("pivot.expected.json");
    let regions: Vec<String> = exp["regions"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let months: Vec<String> = exp["months"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let products: Vec<String> = exp["products"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("pivot.{ext}"), 1) else {
            return;
        };
        let s = &wb.sheets[i];
        // header: "地域", "商品", "1月".."6月", total (the second pivot starts at column M)
        let hr = find_row(s, 0, "地域").expect("pivot header row");
        assert_eq!(s.display(hr, 1), "商品", "{ext}");
        let mcol: Vec<usize> = months
            .iter()
            .map(|m| {
                (0..12)
                    .find(|&c| s.display(hr, c) == m)
                    .expect("month column")
            })
            .collect();
        let tcol = mcol[mcol.len() - 1] + 1;
        assert_eq!(s.display(hr, tcol), "Total Result", "{ext}");

        let mut pending: Vec<usize> = Vec::new(); // product rows waiting for their subtotal row
        let mut seen_products = 0;
        let mut seen_regions = Vec::new();
        for r in hr + 1..s.nrows {
            let a = s.display(r, 0);
            let b = s.display(r, 1);
            if products.iter().any(|p| p == b) {
                pending.push(r);
                continue;
            }
            // A subtotal row ("関西 Sum - 売上") closes a region's group.
            if let Some(region) = regions
                .iter()
                .find(|g| a.starts_with(g.as_str()) && a.contains("Sum"))
            {
                assert_eq!(
                    pending.len(),
                    products.len(),
                    "{ext} {region}: products in group"
                );
                for pr in pending.drain(..) {
                    let p = s.display(pr, 1);
                    seen_products += 1;
                    // the region label sits on the first product row (xlsx) or is blank
                    for (m, &c) in months.iter().zip(&mcol) {
                        let want = sums(&exp, "cell", &format!("{region}|{p}|{m}"));
                        assert_eq!(num(s, pr, c), want, "{ext} {region}/{p}/{m}");
                        assert_eq!(
                            s.display(pr, c),
                            format!("{want}"),
                            "{ext} display {region}/{p}/{m}"
                        );
                    }
                    let want = sums(&exp, "region_product_total", &format!("{region}|{p}"));
                    assert_eq!(num(s, pr, tcol), want, "{ext} {region}/{p} total");
                }
                // subtotal per month and overall
                for (m, &c) in months.iter().zip(&mcol) {
                    let want: f64 = products
                        .iter()
                        .map(|p| sums(&exp, "cell", &format!("{region}|{p}|{m}")))
                        .sum();
                    assert_eq!(num(s, r, c), want, "{ext} {region} subtotal {m}");
                }
                assert_eq!(
                    num(s, r, tcol),
                    sums(&exp, "region_subtotal", region),
                    "{ext} {region} subtotal"
                );
                seen_regions.push(region.clone());
                continue;
            }
            if a == "Total Result" {
                for (m, &c) in months.iter().zip(&mcol) {
                    assert_eq!(
                        num(s, r, c),
                        sums(&exp, "month_total", m),
                        "{ext} grand {m}"
                    );
                }
                assert_eq!(
                    num(s, r, tcol),
                    exp["grand"].as_f64().unwrap(),
                    "{ext} grand total"
                );
                break;
            }
        }
        assert_eq!(
            seen_regions.len(),
            regions.len(),
            "{ext}: every region has a subtotal row"
        );
        assert_eq!(seen_products, regions.len() * products.len(), "{ext}");
    }
}

/// A second pivot on the same sheet, to the right of the first (AVERAGE by product x channel).
#[test]
fn pivot_second_table_on_the_same_sheet_is_read_as_cells_next_to_the_first() {
    let exp = json("pivot.expected.json");
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("pivot.{ext}"), 1) else {
            return;
        };
        let s = &wb.sheets[i];
        assert!(
            s.ncols >= 16,
            "{ext}: both pivots are on the sheet ({} cols)",
            s.ncols
        );
        let hr = (0..s.nrows)
            .find(|&r| s.display(r, 12) == "商品")
            .expect("second pivot header");
        let (web, shop, tot) = (13, 14, 15);
        assert_eq!(
            (s.display(hr, web), s.display(hr, shop), s.display(hr, tot)),
            ("Web", "店舗", "Total Result"),
            "{ext}"
        );
        for p in ["りんご", "みかん", "Pen & Ink <A>", "ぶどう"] {
            let r = (hr + 1..s.nrows)
                .find(|&r| s.display(r, 12) == p)
                .unwrap_or_else(|| panic!("{ext} {p}"));
            for (c, ch) in [(web, "Web"), (shop, "店舗")] {
                let want = sums(&exp, "avg_by_product_channel", &format!("{p}|{ch}"));
                assert!(
                    (num(s, r, c) - want).abs() < 1e-9,
                    "{ext} {p}/{ch}: {} vs {want}",
                    num(s, r, c)
                );
            }
            let want = sums(&exp, "avg_by_product", p);
            assert!((num(s, r, tot) - want).abs() < 1e-9, "{ext} {p} total");
        }
        let r = (hr + 1..s.nrows)
            .find(|&r| s.display(r, 12) == "Total Result")
            .unwrap();
        assert!(
            (num(s, r, web) - sums(&exp, "avg_by_channel", "Web")).abs() < 1e-9,
            "{ext}"
        );
        assert!(
            (num(s, r, shop) - sums(&exp, "avg_by_channel", "店舗")).abs() < 1e-9,
            "{ext}"
        );
        assert!(
            (num(s, r, tot) - exp["avg_all"].as_f64().unwrap()).abs() < 1e-9,
            "{ext}"
        );
        // General is shown the way Excel shows it in a default-width column: 10 significant digits
        let r = (hr + 1..s.nrows)
            .find(|&r| s.display(r, 12) == "ぶどう")
            .unwrap();
        assert_eq!(s.display(r, web), "722.9166667", "{ext}");
    }
}

/// The page (report filter) field is two cells ("地域", "関東") above the table, and the table below
/// shows only that region.
#[test]
fn pivot_with_a_page_filter_shows_the_filter_cells_and_only_the_filtered_totals() {
    let exp = json("pivot.expected.json");
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("pivot.{ext}"), 2) else {
            return;
        };
        let s = &wb.sheets[i];
        let fr = find_row(s, 0, "地域").expect("page field row");
        assert_eq!(s.display(fr, 1), "関東", "{ext}: the selected page");
        let hr = find_row(s, 0, "商品").expect("header");
        for p in ["りんご", "みかん", "Pen & Ink <A>", "ぶどう"] {
            let r = find_row(s, 0, p).unwrap_or_else(|| panic!("{ext} {p}"));
            for (k, m) in ["1月", "2月", "3月", "4月", "5月", "6月"]
                .iter()
                .enumerate()
            {
                assert_eq!(s.display(hr, 1 + k), *m, "{ext}");
                let want = sums(&exp, "cell", &format!("関東|{p}|{m}"));
                assert_eq!(num(s, r, 1 + k), want, "{ext} {p}/{m}");
            }
        }
        let r = find_row(s, 0, "Total Result").unwrap();
        assert_eq!(
            num(s, r, 7),
            exp["kanto_only_grand"].as_f64().unwrap(),
            "{ext}"
        );
    }
}

#[test]
fn pivot_count_table_shows_counts() {
    let exp = json("pivot.expected.json");
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("pivot.{ext}"), 3) else {
            return;
        };
        let s = &wb.sheets[i];
        let hr = find_row(s, 0, "地域").unwrap();
        let (web, shop, tot) = (
            (1..4).find(|&c| s.display(hr, c) == "Web").unwrap(),
            (1..4).find(|&c| s.display(hr, c) == "店舗").unwrap(),
            (1..4)
                .find(|&c| s.display(hr, c) == "Total Result")
                .unwrap(),
        );
        for region in ["北海道", "関東", "関西", "九州"] {
            let r = find_row(s, 0, region).unwrap();
            assert_eq!(
                num(s, r, web),
                sums(&exp, "count_by_region_channel", &format!("{region}|Web")),
                "{ext}"
            );
            assert_eq!(
                num(s, r, shop),
                sums(&exp, "count_by_region_channel", &format!("{region}|店舗")),
                "{ext}"
            );
            assert_eq!(num(s, r, tot), 24.0, "{ext}");
        }
        let r = find_row(s, 0, "Total Result").unwrap();
        assert_eq!(
            (num(s, r, web), num(s, r, shop), num(s, r, tot)),
            (48.0, 48.0, 96.0),
            "{ext}"
        );
    }
}

/// The pivot sheet's own title row (a plain cell above the pivot) and the "Filter" button labels
/// LibreOffice writes are ordinary text.
#[test]
fn pivot_sheet_keeps_the_plain_cells_around_the_pivot() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("pivot.{ext}"), 1) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!(s.display(0, 0), "地域×商品×月 売上 (SUM)", "{ext}");
    }
}

// ---------------------------------------------------------------------------------------------
// objects: chart, picture, shape, text box, comment, conditional format, validation, hyperlink
// ---------------------------------------------------------------------------------------------

#[test]
fn objects_cells_around_charts_pictures_shapes_and_comments_are_read_normally() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("objects.{ext}"), 0) else {
            return;
        };
        assert_eq!(names(&wb), ["売上", "図形のみ"], "{ext}");
        assert_eq!(wb.hidden_sheets, 0, "{ext}");
        let s = &wb.sheets[i];
        let g = grid(s);
        assert_eq!(g[0][..5], ["月", "売上", "前年", "備考", "選択"], "{ext}");
        assert_eq!(
            g[1][..5],
            ["1月", "120", "100", "好調 \u{1F600}", "みかん"],
            "{ext}"
        );
        assert_eq!(g[2][..4], ["2月", "150", "130", "Tom & Jerry <b>"], "{ext}");
        assert_eq!(g[5][..3], ["5月", "175", "150"], "{ext}");
        // a formula below the chart's area keeps its value (and its row position)
        assert_eq!(s.nrows, 30, "{ext}");
        assert_eq!(s.display(29, 0), "グラフの下の行", "{ext}");
        assert_eq!(s.display(29, 1), "735", "{ext}");
        assert!(
            s.formula(29, 1).is_some_and(|f| f.contains("SUM")),
            "{ext}: {:?}",
            s.formula(29, 1)
        );
    }
}

/// Current spec (§6): the comment, the shape's text, the chart and the picture are not read.
#[test]
fn objects_comments_shapes_charts_and_pictures_are_not_shown_current_spec() {
    for ext in EXTS {
        for idx in [0, 1] {
            let Some((wb, i)) = sheet_wb(&format!("objects.{ext}"), idx) else {
                return;
            };
            let all: String = grid(&wb.sheets[i])
                .iter()
                .flatten()
                .cloned()
                .collect::<Vec<_>>()
                .join("|");
            for hidden_text in [
                "コメント",
                "先月比",
                "備考のコメント",
                "図形のテキスト",
                "テキストボックス",
                "グラフ1",
            ] {
                assert!(
                    !all.contains(hidden_text),
                    "{ext} sheet {idx}: {hidden_text:?} must not be a cell"
                );
            }
        }
    }
}

#[test]
fn objects_hyperlinks_show_their_text_not_their_target() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("objects.{ext}"), 0) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!(
            s.display(0, 6),
            "例のリンク",
            "{ext}: HYPERLINK() formula shows its label"
        );
        assert_eq!(
            s.display(1, 6),
            "URL フィールド",
            "{ext}: URL field shows its representation"
        );
        let all: String = grid(s).iter().flatten().cloned().collect();
        assert!(
            !all.contains("example.com") && !all.contains("example.org"),
            "{ext}"
        );
    }
}

#[test]
fn objects_a_sheet_with_only_a_drawing_has_just_its_cells() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("objects.{ext}"), 1) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!((s.nrows, s.ncols), (1, 1), "{ext}");
        assert_eq!(s.display(0, 0), "セルは A1 だけ", "{ext}");
    }
}

// ---------------------------------------------------------------------------------------------
// layout: hidden rows / columns, outline, filter, merges, wrapping, protection
// ---------------------------------------------------------------------------------------------

/// Current spec (§6): konoma does not read row/column visibility. Hidden columns B and D and
/// hidden rows 5 and 6 are all shown. (A file where a hidden row holds secrets would show them.)
#[test]
fn layout_hidden_rows_and_columns_are_all_shown_current_spec() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("layout.{ext}"), 0) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!((s.nrows, s.ncols), (12, 5), "{ext}");
        assert_eq!(
            s.display(1, 1),
            "B列(非表示)",
            "{ext}: hidden column B is shown"
        );
        assert_eq!(
            s.display(1, 3),
            "D列(非表示)",
            "{ext}: hidden column D is shown"
        );
        assert_eq!(
            grid(s)[4],
            ["r5a", "r5b", "r5c", "r5d", "r5e"],
            "{ext}: hidden row 5 is shown"
        );
        assert_eq!(
            grid(s)[5],
            ["r6a", "r6b", "r6c", "r6d", "r6e"],
            "{ext}: hidden row 6 is shown"
        );
    }
}

/// Current spec: rows 3..7 are grouped and collapsed (hidden) in the file; all ten rows are shown.
#[test]
fn layout_collapsed_outline_rows_are_all_shown_current_spec() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("layout.{ext}"), 1) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!(s.nrows, 10, "{ext}");
        for r in 0..10 {
            assert_eq!(s.display(r, 0), format!("行{}", r + 1), "{ext}");
            assert_eq!(num(s, r, 1), 10.0 * (r as f64 + 1.0), "{ext}");
        }
    }
}

/// Current spec: an auto-filter (value > 50) hides rows 2..6 in the file; all rows are shown.
#[test]
fn layout_rows_hidden_by_an_autofilter_are_all_shown_current_spec() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("layout.{ext}"), 2) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!(s.nrows, 11, "{ext}");
        assert_eq!(grid(s)[0], ["地域", "売上"], "{ext}");
        for r in 1..=10 {
            assert_eq!(
                num(s, r, 1),
                10.0 * r as f64,
                "{ext}: row {} (filtered out in Excel) is shown",
                r + 1
            );
        }
        assert_eq!(s.display(1, 0), "西1", "{ext}");
        assert_eq!(s.display(10, 0), "東10", "{ext}");
    }
}

#[test]
fn layout_merged_cells_show_their_value_at_the_top_left_only() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("layout.{ext}"), 3) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!(s.display(0, 0), "見出し(3行×4列の結合)", "{ext}");
        for (r, c) in [
            (0, 1),
            (0, 3),
            (1, 0),
            (2, 3),
            (4, 1),
            (4, 2),
            (5, 4),
            (7, 4),
        ] {
            assert_eq!(
                s.display(r, c),
                "",
                "{ext}: r{} c{} is covered by a merge",
                r + 1,
                c + 1
            );
        }
        assert_eq!(s.display(4, 0), "横結合", "{ext}");
        assert_eq!(s.display(4, 4), "縦結合", "{ext}");
        assert_eq!(s.display(8, 0), "結合の隣", "{ext}");
        assert_eq!(num(s, 8, 1), 42.0, "{ext}");
    }
}

fn mr(row0: u32, col0: u32, row1: u32, col1: u32) -> MergeRange {
    MergeRange {
        row0,
        col0,
        row1,
        col1,
    }
}

#[test]
fn layout_merged_ranges_are_reported_for_xlsx_and_xls() {
    for ext in ["xlsx", "xls"] {
        let Some((wb, i)) = sheet_wb(&format!("layout.{ext}"), 3) else {
            return;
        };
        let mut m = wb.sheets[i].merges.clone();
        m.sort_by_key(|r| (r.row0, r.col0));
        assert_eq!(m, [mr(0, 0, 2, 3), mr(4, 0, 4, 2), mr(4, 4, 7, 4)], "{ext}");
    }
}

/// `Sheet::merges` is "the merged ranges as the file declares them": for ods they come from the
/// format pass (`table:number-columns-spanned` / `number-rows-spanned`).
#[test]
fn layout_merged_ranges_are_reported_for_ods_too() {
    let Some((wb, i)) = sheet_wb("layout.ods", 3) else {
        return;
    };
    let mut m = wb.sheets[i].merges.clone();
    m.sort_by_key(|r| (r.row0, r.col0));
    assert_eq!(m, [mr(0, 0, 2, 3), mr(4, 0, 4, 2), mr(4, 4, 7, 4)]);
}

#[test]
fn layout_multi_line_and_long_text_is_kept_whole() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("layout.{ext}"), 4) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!(s.display(0, 0), "1行目\n2行目\n3行目", "{ext}");
        assert_eq!(s.display(0, 1), "隣のセル", "{ext}");
        let long = s.display(1, 0);
        assert!(
            long.starts_with("long あいうえお") && long.chars().count() == 5 + 400,
            "{ext}: {}",
            long.chars().count()
        );
        // runs of spaces and NBSP survive
        if ext != "ods" {
            assert_eq!(s.display(2, 0), "tab\there and \u{a0}nbsp", "{ext}: tab");
        }
        assert!(s.display(2, 0).ends_with("here and \u{a0}nbsp"), "{ext}");
        assert_eq!(s.display(3, 0), "a   three spaces", "{ext}");
        assert_eq!(s.display(4, 0), "  leading two", "{ext}");
        assert_eq!(s.display(5, 0), "trailing  ", "{ext}");
    }
}

/// ods writes a tab as `<text:tab/>`, which calamine drops ("tabhere"); the format pass puts it back.
#[test]
fn layout_ods_tab_characters_are_kept() {
    let Some((wb, i)) = sheet_wb("layout.ods", 4) else {
        return;
    };
    assert_eq!(wb.sheets[i].display(2, 0), "tab\there and \u{a0}nbsp");
}

#[test]
fn layout_protected_sheet_is_read_like_any_other() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("layout.{ext}"), 5) else {
            return;
        };
        assert_eq!(names(&wb).len(), 6, "{ext}");
        assert_eq!(
            grid(&wb.sheets[i]),
            [vec!["保護されたシート"], vec!["123"]],
            "{ext}"
        );
    }
}

// ---------------------------------------------------------------------------------------------
// formulas
// ---------------------------------------------------------------------------------------------

#[test]
fn formulas_show_the_value_saved_with_the_file() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("formulas.{ext}"), 1) else {
            return;
        };
        assert_eq!(
            names(&wb),
            ["入力", "計算", "エラー", "配列", "揮発"],
            "{ext}"
        );
        let s = &wb.sheets[i];
        let want: [(usize, &str); 13] = [
            (0, "20"),             // SUM(named range)
            (1, "360"),            // 'input'.B2 * 'input'.C2 (cross-sheet)
            (2, "2010"),           // SUMPRODUCT across sheets
            (3, "2211"),           // ROUND(B3*(1+named cell))
            (4, "合計: 2,010 円"), // text concatenation with TEXT()
            (5, "TRUE"),           // boolean result
            (6, "80"),             // VLOOKUP
            (7, "高い"),
            (9, "0.3"), // 0.1+0.2
            (10, "1E+300"),
            (11, "1E-300"),
            (12, ""), // ="" is an empty string result
            (13, "あああああ"),
        ];
        for (r, v) in want {
            assert_eq!(s.display(r, 1), v, "{ext} 計算!B{}", r + 1);
        }
        // the formulas themselves are available for the cell detail
        for r in [0, 1, 2, 3, 4, 5, 6, 7] {
            assert!(
                s.formula(r, 1).is_some(),
                "{ext} 計算!B{} has a formula",
                r + 1
            );
        }
        assert!(
            s.formula(1, 1).unwrap().contains("入力"),
            "{ext}: {:?}",
            s.formula(1, 1)
        );
        // a formula result that is a date is a date, shown with the saved format
        assert!(
            matches!(
                s.cell(8, 1).unwrap().value,
                CellValue::DateTime { .. } | CellValue::DateTimeIso(_)
            ),
            "{ext}"
        );
        assert_eq!(s.cell(5, 1).unwrap().cell_type(), CellType::Bool, "{ext}");
    }
}

#[test]
fn formulas_named_ranges_and_cross_sheet_inputs_are_plain_values() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("formulas.{ext}"), 0) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!(s.display(4, 0), "Pen & Ink", "{ext}");
        assert_eq!(s.display(0, 4), "0.1", "{ext}");
    }
}

#[test]
fn formulas_error_values_are_shown_the_excel_way() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("formulas.{ext}"), 2) else {
            return;
        };
        let s = &wb.sheets[i];
        // (LibreOffice writes #NUM! / #NULL! as #VALUE! into xlsx/xls/ods; the file is what counts.)
        for (r, want) in [
            (0, "#DIV/0!"),
            (1, "#N/A"),
            (2, "#NAME?"),
            (3, "#VALUE!"),
            (4, "#REF!"),
        ] {
            assert_eq!(s.display(r, 1), want, "{ext} エラー!B{}", r + 1);
            assert_eq!(s.cell(r, 1).unwrap().cell_type(), CellType::Error, "{ext}");
        }
        let all: String = grid(s).iter().flatten().cloned().collect();
        assert!(
            !all.contains("Err:"),
            "{ext}: LibreOffice-internal error text must never appear"
        );
        // an empty reference adds as zero: no error
        assert_eq!(s.display(7, 1), "1", "{ext}");
    }
}

/// Every Excel error code, written the way Excel writes it (`t="e"`).
#[test]
fn formulas_every_excel_error_code_in_an_xlsx_cell() {
    let Some((wb, i)) = sheet_wb("special.xlsx", 0) else {
        return;
    };
    let s = &wb.sheets[i];
    let row = 8; // row 9
    let got: Vec<&str> = (0..7).map(|c| s.display(row, c)).collect();
    assert_eq!(
        got,
        ["#DIV/0!", "#N/A", "#NAME?", "#NULL!", "#NUM!", "#REF!", "#VALUE!"],
        "{got:?}"
    );
}

/// Excel 365 writes `#SPILL!` / `#CALC!` / `#FIELD!` ... for dynamic-array and data-type errors.
/// `calamine` 0.36 knows only the classic seven (even `#GETTING_DATA` is accepted in xls/xlsb but
/// not in xlsx) and rejects the whole sheet as corrupt, so one such cell hides every other cell of
/// the sheet; konoma's own xlsx reader (`xlsx.rs`) takes the error text as the file wrote it.
/// Either way, the other sheets of the workbook stay reachable.
#[test]
fn newer_error_codes_do_not_break_the_workbook() {
    let Some(p) = file("newerrors.xlsx") else {
        return;
    };
    let wb = open_lenient(&p, 4);
    assert_eq!(
        names(&wb),
        ["スピル", "カルク", "フィールド", "取得中", "正常"]
    );
    assert_eq!(wb.sheets[4].display(0, 0), "fine");
}

fn open_lenient(path: &Path, idx: usize) -> Workbook {
    load_workbook_sheet(path, &LoadOptions::default(), idx).unwrap()
}

#[test]
fn newer_error_codes_are_shown_like_any_other_error() {
    let Some(p) = file("newerrors.xlsx") else {
        return;
    };
    for (idx, code) in [
        (0, "#SPILL!"),
        (1, "#CALC!"),
        (2, "#FIELD!"),
        (3, "#GETTING_DATA"),
    ] {
        let wb = open_lenient(&p, idx);
        assert!(
            wb.sheet_error.is_none(),
            "sheet {idx}: {:?}",
            wb.sheet_error
        );
        let s = &wb.sheets[idx];
        assert_eq!(
            s.display(0, 0),
            "before",
            "{code}: the cells around it are still shown"
        );
        assert_eq!(s.display(0, 1), code);
        assert_eq!(s.display(0, 2), "after");
    }
}

#[test]
fn formulas_array_formulas_show_every_result_cell() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("formulas.{ext}"), 3) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!(num(s, 0, 3), 140.0, "{ext}: {{=SUM(A1:A3*B1:B3)}}");
        assert_eq!(
            [num(s, 2, 3), num(s, 3, 3), num(s, 4, 3)],
            [10.0, 40.0, 90.0],
            "{ext}: multi-cell array"
        );
        let m = [[num(s, 0, 7), num(s, 0, 8)], [num(s, 1, 7), num(s, 1, 8)]];
        assert_eq!(m, [[7.0, 10.0], [15.0, 22.0]], "{ext}: MMULT");
        assert_eq!(s.display(2, 2), "要素ごとの積", "{ext}");
    }
}

/// Volatile functions: whatever the file saved is shown, never recalculated; the kind is right.
#[test]
fn formulas_volatile_functions_show_their_saved_values() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("formulas.{ext}"), 4) else {
            return;
        };
        let s = &wb.sheets[i];
        assert!(
            matches!(
                s.cell(0, 0).unwrap().value,
                CellValue::DateTime { .. } | CellValue::DateTimeIso(_)
            ),
            "{ext} NOW()"
        );
        assert!(
            matches!(
                s.cell(1, 0).unwrap().value,
                CellValue::DateTime { .. } | CellValue::DateTimeIso(_)
            ),
            "{ext} TODAY()"
        );
        let r = num(s, 2, 0);
        assert!((0.0..1.0).contains(&r), "{ext} RAND() = {r}");
        // the year of NOW() in the file is the year it was made
        assert!(
            s.display(0, 0).contains("/26 ") || s.display(0, 0).contains("2026"),
            "{ext}: {}",
            s.display(0, 0)
        );
        assert_eq!(s.display(3, 0), "00:00:00", "{ext}: NOW()-NOW()");
    }
}

/// openpyxl writes a formula without a cached value (Excel computes it on open). konoma never
/// calculates, so such a cell shows nothing (but its formula is in the cell detail).
#[test]
fn formulas_without_a_saved_value_show_nothing_current_spec() {
    let Some((wb, i)) = sheet_wb("special.xlsx", 0) else {
        return;
    };
    let s = &wb.sheets[i];
    assert_eq!(s.display(1, 5), "", "F2 has no cached value");
    assert!(
        s.formula(1, 5).is_some_and(|f| f.contains("SUBTOTAL")),
        "{:?}",
        s.formula(1, 5)
    );
    assert_eq!(s.display(2, 5), "2580", "F3 has one");
}

// ---------------------------------------------------------------------------------------------
// number formats
// ---------------------------------------------------------------------------------------------

/// What Excel shows (English UI), for `formats.xlsx` and `formats.xls`. Row index = case index + 1.
/// Cases where Excel's own text is not certain (sub-second rounding) are not pinned here.
const FORMATS_EXCEL: &[(&str, &str)] = &[
    ("和暦(令和)", "令和8年10月5日"),
    ("和暦(平成1年)", "平成1年1月8日"),
    ("和暦(昭和)", "昭和55年04月29日"),
    ("西暦 日本語曜日", "2026年10月05日 (月)"),
    ("英語曜日・月名", "Monday, October 5, 2026"),
    ("ISO 日付", "2026-10-05"),
    ("24 時間超 [h]:mm:ss", "36:00:00"),
    ("100.25 日 [h]:mm", "2406:00"),
    ("経過分 [mm]:ss", "61:12"),
    ("時刻 AM/PM", "1:30 PM"),
    ("負数の赤", "-1,235"),
    ("負数の括弧(赤)", "(1,234.50)"),
    ("正数", "1,235"),
    ("ゼロ区画", "ゼロ"),
    ("分数 # ?/?", " 3/4"),
    ("分数 帯分数", "3 14/99"),
    ("指数 0.00E+00", "1.23E+04"),
    ("指数 ##0.0E+0", "12.3E+3"),
    ("指数 微小", "1.23E-04"),
    ("通貨 円", "¥1,500"),
    ("通貨 円 負", "-¥1,500"),
    ("通貨 ユーロ", "€ 1,234.50"),
    ("通貨 ドル", "$1,234.50"),
    ("通貨 ウォン", "₩1,234,567"),
    ("通貨 ポンド", "£99.50"),
    ("パーセント", "25.6%"),
    ("千単位", "1,235K"),
    ("条件付き", "12.3万"),
    ("色と条件", "-5"),
    ("ゼロ詰め", "000123"),
    ("電話番号", "090-1234-5678"),
    ("テキスト書式 @", "00123"),
    ("文字列に書式", "【あいう】"),
    ("会計 _ と *", " 1,234.50 "),
    ("丸め 0.5 → 1", "1"),
    ("丸め 2.5 → 3", "3"),
    ("丸め 0.285 小数2", "0.29"),
    ("日付+時刻", "2026/10/05 18:00:00"),
    // Excel's serial 0 is "1900-01-00" and serial 60 is the non-existent 1900-02-29
    ("通し日付 0", "1900-01-00"),
    ("1900 閏年 60", "1900-02-29"),
    // General in a default-width column: at most ~11 characters (Excel switches to E notation)
    ("大きい数 General", "1.23457E+11"),
    ("小数 General", "0.333333333"),
];

fn formats_by_label(s: &Sheet) -> std::collections::HashMap<String, String> {
    (1..s.nrows)
        .map(|r| (s.display(r, 0).to_string(), s.display(r, 1).to_string()))
        .collect()
}

#[test]
fn formats_xlsx_and_xls_show_what_excel_shows() {
    for ext in ["xlsx", "xls"] {
        let Some((wb, i)) = sheet_wb(&format!("formats.{ext}"), 0) else {
            return;
        };
        let m = formats_by_label(&wb.sheets[i]);
        assert_eq!(m.len(), 43, "{ext}: every case row is there");
        for (label, want) in FORMATS_EXCEL {
            assert_eq!(
                m.get(*label).map(String::as_str),
                Some(*want),
                "{ext}: {label}"
            );
        }
    }
}

/// Sub-second display: 0.000694444 d is 59.99999 s. Excel carries into the minute.
#[test]
fn formats_fractional_seconds_carry_instead_of_showing_sixty() {
    let Some((wb, i)) = sheet_wb("formats.xlsx", 0) else {
        return;
    };
    let m = formats_by_label(&wb.sheets[i]);
    let v = &m["時刻 小数秒"];
    assert!(v == "01:00.00" || v == "00:59.99", "{v}");
    assert!(!v.contains(":60"), "{v}");
}

#[test]
fn formats_ods_matches_excel_for_every_family() {
    let Some((wb, i)) = sheet_wb("formats.ods", 0) else {
        return;
    };
    let m = formats_by_label(&wb.sheets[i]);
    let skip = [
        // LibreOffice's day 0 is 1899-12-30 (Excel's is "1900-01-00"): checked below
        "通し日付 0",
        // the weekday name `aaa` is English here: an ods style carries no locale for it
        "西暦 日本語曜日",
        // ods stores real dates (no serial): 1900-02-29 cannot exist, LibreOffice's 1900-02-28
        "1900 閏年 60",
        // General: not the same in ods (checked below)
        "大きい数 General",
        "小数 General",
    ];
    for (label, want) in FORMATS_EXCEL {
        if skip.contains(label) {
            continue;
        }
        assert_eq!(
            m.get(*label).map(String::as_str),
            Some(*want),
            "ods: {label}"
        );
    }
    assert_eq!(m["通し日付 0"], "1899-12-30");
    assert_eq!(m["西暦 日本語曜日"], "2026年10月05日 (Mon)");
    assert_eq!(m["1900 閏年 60"], "1900-02-28");
    assert_eq!(m["大きい数 General"], "1.23457E+11");
    assert_eq!(m["小数 General"], "0.333333333");
}

/// LibreOffice writes the elapsed-time flag `truncate-on-overflow="false"` on the `number:time-style`
/// element (not on its children): `[h]:mm:ss` of 36 hours must show 36:00:00, not 12:00:00.
#[test]
fn formats_ods_elapsed_time_shows_hours_beyond_24() {
    let Some((wb, i)) = sheet_wb("formats.ods", 0) else {
        return;
    };
    let m = formats_by_label(&wb.sheets[i]);
    assert_eq!(m["24 時間超 [h]:mm:ss"], "36:00:00");
    assert_eq!(m["100.25 日 [h]:mm"], "2406:00");
    assert_eq!(m["経過分 [mm]:ss"], "61:12");
}

#[test]
fn formats_ods_mixed_fractions_keep_the_integer_part() {
    let Some((wb, i)) = sheet_wb("formats.ods", 0) else {
        return;
    };
    let m = formats_by_label(&wb.sheets[i]);
    assert_eq!(m["分数 帯分数"], "3 14/99");
    assert_eq!(m["分数 # ?/?"], " 3/4");
}

#[test]
fn formats_ods_digits_with_embedded_text_keep_the_literal() {
    let Some((wb, i)) = sheet_wb("formats.ods", 0) else {
        return;
    };
    let m = formats_by_label(&wb.sheets[i]);
    assert_eq!(m["電話番号"], "090-1234-5678");
}

#[test]
fn formats_ods_engineering_notation_uses_the_exponent_interval() {
    let Some((wb, i)) = sheet_wb("formats.ods", 0) else {
        return;
    };
    let m = formats_by_label(&wb.sheets[i]);
    assert_eq!(m["指数 ##0.0E+0"], "12.3E+3");
}

#[test]
fn formats_ods_the_null_date_itself_is_a_date() {
    let Some((wb, i)) = sheet_wb("formats.ods", 0) else {
        return;
    };
    let m = formats_by_label(&wb.sheets[i]);
    assert!(!m["通し日付 0"].contains('#'), "{}", m["通し日付 0"]);
}

#[test]
fn formats_1904_date_system_shows_the_same_dates() {
    // One row per case: (label, display). The values are stored relative to 1904-01-01.
    let want = [
        ("1904 基準の日付", "2026-10-05"),
        ("1904 基準 0", "1904-01-01"),
        ("1904 基準 1462", "1908-01-02"),
        ("1904 基準 日付時刻", "2026-10-05 12:00"),
    ];
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("date1904.{ext}"), 0) else {
            return;
        };
        // xlsx/xls say so in the file; ods stores real dates, so there is nothing to say
        assert_eq!(wb.date1904, ext != "ods", "{ext}");
        let m = formats_by_label(&wb.sheets[i]);
        for (label, text) in want {
            assert_eq!(m[label], text, "{ext}: {label}");
        }
    }
    for ext in ["xlsx", "xls"] {
        let (wb, i) = sheet_wb(&format!("date1904.{ext}"), 0).unwrap();
        assert_eq!(
            formats_by_label(&wb.sheets[i])["1904 基準 経過"],
            "36:00",
            "{ext}"
        );
    }
}

#[test]
fn formats_1904_ods_elapsed_time() {
    let Some((wb, i)) = sheet_wb("date1904.ods", 0) else {
        return;
    };
    assert_eq!(formats_by_label(&wb.sheets[i])["1904 基準 経過"], "36:00");
}

// ---------------------------------------------------------------------------------------------
// sheets
// ---------------------------------------------------------------------------------------------

const SHEET_NAMES_VISIBLE: [&str; 18] = [
    "売上",
    "Sheet 2",
    "A&B",
    "売上 (2026)",
    "経費・予算",
    "😀絵文字",
    "R&D <x>",
    "Q1",
    "Q2",
    "Q3",
    "Q4",
    "第十三シート",
    "サマリー",
    "メモ",
    "付録A",
    "付録B",
    "最後から2番目",
    "最後",
];

#[test]
fn sheets_twenty_sheets_two_hidden_japanese_and_symbol_names() {
    for ext in EXTS {
        let Some(p) = file(&format!("sheets.{ext}")) else {
            return;
        };
        let wb = open(&p, 0);
        assert_eq!(names(&wb), SHEET_NAMES_VISIBLE, "{ext}");
        assert_eq!(
            wb.hidden_sheets, 2,
            "{ext}: O'Brien and データ#7 are hidden"
        );
        // every visible sheet can be loaded on its own and holds its own cell
        for (i, n) in SHEET_NAMES_VISIBLE.iter().enumerate() {
            let wb = open(&p, i);
            assert_eq!(wb.loaded_index(), Some(i), "{ext} {n}");
            let s = &wb.sheets[i];
            if *n == "Q1" || *n == "Q2" {
                continue;
            }
            // "シート <position among all 20>: <name>"
            assert!(
                s.display(0, 0).ends_with(&format!(": {n}")),
                "{ext} {n}: {}",
                s.display(0, 0)
            );
            assert!(num(s, 0, 1) >= 1.0, "{ext} {n}");
        }
    }
}

#[test]
fn sheets_asking_past_the_last_sheet_clamps_to_the_last() {
    let Some(p) = file("sheets.xlsx") else {
        return;
    };
    let wb = open(&p, 99);
    assert_eq!(wb.loaded_index(), Some(17));
}

#[test]
fn sheets_a_used_range_that_starts_at_c5_keeps_its_a1_addresses() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("sheets.{ext}"), 7) else {
            return;
        };
        let s = &wb.sheets[i];
        assert_eq!(s.display(4, 2), "C5 から始まる", "{ext}");
        assert_eq!(num(s, 5, 3), 66.0, "{ext}");
        assert_eq!(s.display(0, 0), "シート 10: Q1", "{ext}");
    }
}

#[test]
fn sheets_an_empty_sheet_loads_as_zero_by_zero() {
    for ext in EXTS {
        let Some((wb, i)) = sheet_wb(&format!("sheets.{ext}"), 8) else {
            return;
        };
        assert_eq!((wb.sheets[i].nrows, wb.sheets[i].ncols), (0, 0), "{ext}");
        let Some(p) = file(&format!("empty.{ext}")) else {
            return;
        };
        let wb = open(&p, 0);
        assert_eq!(names(&wb), ["Sheet1"], "{ext}");
        assert_eq!((wb.sheets[0].nrows, wb.sheets[0].ncols), (0, 0), "{ext}");
    }
}

/// openpyxl: a very-hidden sheet and a hidden sheet are both counted as hidden and not listed; a
/// chart sheet (a sheet that is only a chart) is neither listed nor counted.
#[test]
fn sheets_very_hidden_hidden_and_chart_sheets() {
    let Some(p) = file("special.xlsx") else {
        return;
    };
    let wb = open(&p, 0);
    assert_eq!(names(&wb), ["表", "リッチ", "最後の表"]);
    assert_eq!(
        wb.hidden_sheets, 2,
        "隠し + 超隠し; the chart sheet is not a hidden sheet"
    );
    // the sheet after the chart sheet is reachable and is the third visible one
    let wb = open(&p, 2);
    assert_eq!(wb.sheets[2].display(0, 0), "after the chart sheet");
}

#[test]
fn sheets_wide_sheet_reaches_column_kn() {
    let Some((wb, i)) = sheet_wb("widesheet.xlsx", 0) else {
        return;
    };
    let s = &wb.sheets[i];
    assert_eq!((s.nrows, s.ncols), (2, 301));
    assert_eq!(s.display(0, 299), "299");
    assert_eq!(s.display(1, 300), "桁 KN");
    assert!(!s.cols_truncated);
}

// ---------------------------------------------------------------------------------------------
// openpyxl-only content: tables, rich text, inline strings, typed cells
// ---------------------------------------------------------------------------------------------

#[test]
fn special_excel_table_is_plain_cells_with_its_header() {
    let Some((wb, i)) = sheet_wb("special.xlsx", 0) else {
        return;
    };
    let s = &wb.sheets[i];
    assert_eq!(grid(s)[0][..4], ["地域", "商品", "数量", "金額"]);
    assert_eq!(grid(s)[1][..4], ["東", "りんご", "3", "360"]);
    assert_eq!(grid(s)[5][..4], ["東", "みかん", "1", "80"]);
}

#[test]
fn special_inline_strings_string_formula_results_and_typed_cells() {
    let Some((wb, i)) = sheet_wb("special.xlsx", 0) else {
        return;
    };
    let s = &wb.sheets[i];
    // row 8: t="inlineStr", t="str" with a formula, t="str" value only, t="b", t="e"
    assert_eq!(s.display(7, 0), "インライン文字列");
    assert_eq!(s.cell(7, 0).unwrap().cell_type(), CellType::Text);
    assert_eq!(s.display(7, 1), "ab");
    assert_eq!(s.formula(7, 1), Some("\"a\"&\"b\""));
    assert_eq!(s.display(7, 2), "str-typed value");
    assert_eq!(s.display(7, 3), "TRUE");
    assert_eq!(s.cell(7, 3).unwrap().cell_type(), CellType::Bool);
    assert_eq!(s.display(7, 4), "#REF!");
}

#[test]
fn special_rich_text_shows_its_plain_text_and_escapes_are_decoded() {
    let Some((wb, i)) = sheet_wb("special.xlsx", 1) else {
        return;
    };
    let s = &wb.sheets[i];
    assert_eq!(
        s.display(0, 0),
        "普通太字赤 と 斜体",
        "rich text runs are joined"
    );
    assert_eq!(
        s.display(1, 0),
        "  leading and trailing  ",
        "xml:space=preserve"
    );
    assert_eq!(s.display(2, 0), "line1\nline2");
    assert_eq!(s.display(3, 0), "x\u{b}vt", "_x000B_ is a vertical tab");
    assert_eq!(
        s.display(4, 0),
        "A literal escape text",
        "_x0041_ is the letter A"
    );
}

#[test]
fn special_dates_times_durations_booleans_errors_and_extreme_numbers() {
    let Some((wb, i)) = sheet_wb("special.xlsx", 1) else {
        return;
    };
    let s = &wb.sheets[i];
    assert_eq!(s.display(5, 0), "2026-10-05 13:30:15");
    assert_eq!(s.display(6, 0), "2026-10-05");
    assert_eq!(s.display(7, 0), "7:05:09");
    assert_eq!(s.display(8, 0), "36:30:00");
    assert_eq!((s.display(0, 1), s.display(1, 1)), ("TRUE", "FALSE"));
    assert_eq!((s.display(2, 1), s.display(3, 1)), ("#DIV/0!", "#N/A"));
    assert_eq!(s.display(0, 2), "1.5E+300");
    assert_eq!(s.display(1, 2), "0", "negative zero is shown as 0");
    assert_eq!(s.display(2, 2), "123456789.1");
    assert_eq!(s.display(3, 2), "1E+15");
    assert_eq!(s.display(4, 2), "9.0072E+15");
}

// ---------------------------------------------------------------------------------------------
// encrypted
// ---------------------------------------------------------------------------------------------

#[test]
fn encrypted_xlsx_and_xls_are_reported_as_encrypted() {
    for ext in ["xlsx", "xls"] {
        let Some(p) = file(&format!("encrypted.{ext}")) else {
            return;
        };
        assert_eq!(
            load_workbook_sheet(&p, &LoadOptions::default(), 0),
            Err(OfficeError::Encrypted),
            "{ext}"
        );
        assert_eq!(
            load_workbook(&p, &LoadOptions::default()),
            Err(OfficeError::Encrypted),
            "{ext}"
        );
    }
}

/// LibreOffice 25+ encrypts an ods as one `encrypted-package` entry (AES-GCM, Argon2). The package
/// has no `content.xml`; the clear `mimetype` and the manifest tell it is an encrypted spreadsheet.
#[test]
fn encrypted_ods_is_reported_as_encrypted() {
    let Some(p) = file("encrypted.ods") else {
        return;
    };
    assert_eq!(
        load_workbook_sheet(&p, &LoadOptions::default(), 0),
        Err(OfficeError::Encrypted)
    );
}

/// Whatever the reason, an encrypted ods is refused without a panic or a hang (today: Unsupported).
#[test]
fn encrypted_ods_is_refused_cleanly() {
    let Some(p) = file("encrypted.ods") else {
        return;
    };
    let r = load_workbook_sheet(&p, &LoadOptions::default(), 0);
    assert!(
        matches!(
            r,
            Err(OfficeError::Encrypted) | Err(OfficeError::Unsupported)
        ),
        "{r:?}"
    );
}

// ---------------------------------------------------------------------------------------------
// a sheet over the row cap
// ---------------------------------------------------------------------------------------------

/// 120,000 data rows x 3 columns plus a small second sheet, as an xlsx (generated here: a file this
/// size is not kept in the repository).
fn big_xlsx(dir: &crate::test_support::TmpDir) -> PathBuf {
    let mut rows = String::from(
        r#"<row r="1"><c r="A1" t="inlineStr"><is><t>行番号</t></is></c><c r="B1" t="inlineStr"><is><t>二乗</t></is></c><c r="C1" t="inlineStr"><is><t>ラベル</t></is></c></row>"#,
    );
    for i in 1..=120_000u64 {
        let r = i + 1;
        rows += &format!(
            r#"<row r="{r}"><c r="A{r}"><v>{i}</v></c><c r="B{r}"><v>{}</v></c><c r="C{r}" t="inlineStr"><is><t>行{i}</t></is></c></row>"#,
            i * i
        );
    }
    let small = r#"<row r="1"><c r="A1" t="inlineStr"><is><t>小さいシート</t></is></c></row>"#;
    let p = dir.join("big.xlsx");
    crate::e2e_tests::build_xlsx(
        &p,
        &[("大", "visible", &rows, ""), ("小", "visible", small, "")],
    );
    p
}

/// The same workbook as an ods.
fn big_ods(dir: &crate::test_support::TmpDir) -> PathBuf {
    const NS: &str = concat!(
        r#"xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" "#,
        r#"xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" "#,
        r#"xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0""#
    );
    let s = |t: &str| {
        format!(
            r#"<table:table-cell office:value-type="string"><text:p>{t}</text:p></table:table-cell>"#
        )
    };
    let f = |v: u64| {
        format!(
            r#"<table:table-cell office:value-type="float" office:value="{v}"><text:p>{v}</text:p></table:table-cell>"#
        )
    };
    let mut rows = format!(
        "<table:table-row>{}{}{}</table:table-row>",
        s("行番号"),
        s("二乗"),
        s("ラベル")
    );
    for i in 1..=120_000u64 {
        rows += &format!(
            "<table:table-row>{}{}{}</table:table-row>",
            f(i),
            f(i * i),
            s(&format!("行{i}"))
        );
    }
    let content = format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><office:document-content {NS} office:version="1.3"><office:body><office:spreadsheet><table:table table:name="大">{rows}</table:table><table:table table:name="小"><table:table-row>{}</table:table-row></table:table></office:spreadsheet></office:body></office:document-content>"#,
        s("小さいシート")
    );
    let manifest = r#"<?xml version="1.0" encoding="UTF-8"?><manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.3"><manifest:file-entry manifest:full-path="/" manifest:media-type="application/vnd.oasis.opendocument.spreadsheet"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/></manifest:manifest>"#;
    let bytes = tests::deflated(&[
        (
            "mimetype",
            b"application/vnd.oasis.opendocument.spreadsheet",
        ),
        ("content.xml", content.as_bytes()),
        ("META-INF/manifest.xml", manifest.as_bytes()),
    ]);
    let p = dir.join("big.ods");
    std::fs::write(&p, bytes).unwrap();
    p
}

#[test]
fn big_sheet_shows_its_beginning_and_is_marked_capped() {
    let cap = LoadOptions::default().limits.max_rows;
    let dir = tests::tmp("complex_big");
    for (ext, p) in [("xlsx", big_xlsx(&dir)), ("ods", big_ods(&dir))] {
        let wb = open(&p, 0);
        assert_eq!(names(&wb), ["大", "小"], "{ext}");
        let s = &wb.sheets[0];
        assert!(
            s.rows_truncated,
            "{ext}: 120,000 rows is over the cap of {cap}"
        );
        assert!(
            s.nrows <= cap + 1 && s.nrows >= cap,
            "{ext}: {} rows",
            s.nrows
        );
        assert_eq!(grid(s)[0], ["行番号", "二乗", "ラベル"], "{ext}");
        assert_eq!(grid(s)[1], ["1", "1", "行1"], "{ext}");
        assert_eq!(grid(s)[1000], ["1000", "1000000", "行1000"], "{ext}");
        // the last kept row is a real row of the file, not a partial one
        let last = s.nrows - 1;
        assert_eq!(s.display(last, 0), last.to_string(), "{ext}");
        assert_eq!(s.display(last, 2), format!("行{last}"), "{ext}");
        // the second sheet is still reachable on its own
        let wb2 = open(&p, 1);
        assert_eq!(wb2.sheets[1].display(0, 0), "小さいシート", "{ext}");
        assert!(!wb2.sheets[1].rows_truncated, "{ext}");
    }
}
